apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plannify-dev-admin-api
  name: plannify-dev-admin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plannify-dev-admin-api
  template:
    metadata:
      labels:
        app: plannify-dev-admin-api
    spec:
      containers:
        - image: ghcr.io/plannify-truck-driver-app/admin-api:0.0.1-dev.0
          name: plannify-dev-admin-api
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "1m"
              memory: "8Mi"
            limits:
              cpu: "10m"
              memory: "24Mi"
          ports:
            - containerPort: 3000
              name: web
          env:
            - name: RUST_LOG
              value: DEBUG
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-admin-api
                  key: JWT_SECRET
            - name: ACCESS_TOKEN_DURATION_MINUTES
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-admin-api
                  key: ACCESS_TOKEN_DURATION_MINUTES
            - name: REFRESH_TOKEN_DURATION_MINUTES
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-admin-api
                  key: REFRESH_TOKEN_DURATION_MINUTES
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-admin-api
                  key: DATABASE_URL
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: plannify-dev-admin-api
spec:
  ports:
    - name: http
      port: 3000
  selector:
    app: plannify-dev-admin-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plannify-dev-admin-api
spec:
  rules:
    - host: api.dev.plannify.be
      http:
        paths:
          - backend:
              service:
                name: plannify-dev-admin-api
                port:
                  number: 3000
            path: /admin
            pathType: Prefix
  tls:
    - secretName: dev-plannify-be-tls
