apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plannify-dev-admin-api
  name: plannify-dev-admin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plannify-dev-admin-api
  template:
    metadata:
      labels:
        app: plannify-dev-admin-api
    spec:
      containers:
        - image: ghcr.io/plannify-truck-driver-app/admin-api:0.0.1-dev.0
          name: plannify-dev-admin-api
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "150m"
              memory: "128Mi"
          ports:
            - containerPort: 3000
              name: web
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: plannify-dev-admin-api
spec:
  ports:
    - name: http
      port: 3000
  selector:
    app: plannify-dev-admin-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plannify-dev-admin-api
spec:
  rules:
    - host: api.dev.plannify.be
      http:
        paths:
          - backend:
              service:
                name: plannify-dev-admin-api
                port:
                  number: 3000
  tls:
    - secretName: dev-plannify-be-tls
