apiVersion: apps/v1
kind: Deployment
metadata:
  name: plannify-postgresql
  namespace: plannify-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plannify-postgresql
  template:
    metadata:
      labels:
        app: plannify-postgresql
    spec:
      containers:
        - image: postgres:16
          name: plannify-postgresql
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "60m"
              memory: "128Mi"
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-postgresql
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-postgresql
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-postgresql
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data
          volumeMounts:
            - name: postgres-pv
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: plannify-postgresql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: plannify-postgresql
  namespace: plannify-dev
spec:
  type: ClusterIP
  selector:
    app: plannify-postgresql
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plannify-postgresql-pvc
  namespace: plannify-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
