apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plannify-dev-admin-api
  name: plannify-dev-admin-api
  namespace: plannify-dev
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: plannify-dev-admin-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: plannify-dev-admin-api
    spec:
      containers:
        - image: ghcr.io/plannify-truck-driver-app/admin-api:0.0.1-dev.80
          name: plannify-dev-admin-api
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "4m"
              memory: "8Mi"
            limits:
              cpu: "16m"
              memory: "24Mi"
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /admin/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: RUST_LOG
              value: DEBUG
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-admin-api
                  key: JWT_SECRET
            - name: ACCESS_TOKEN_DURATION_MINUTES
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-admin-api
                  key: ACCESS_TOKEN_DURATION_MINUTES
            - name: REFRESH_TOKEN_DURATION_MINUTES
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-admin-api
                  key: REFRESH_TOKEN_DURATION_MINUTES
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-admin-api
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: plannify-dev-admin-api
                  key: REDIS_URL
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: plannify-dev-admin-api
  namespace: plannify-dev
spec:
  type: ClusterIP
  selector:
    app: plannify-dev-admin-api
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plannify-dev-admin-api
  namespace: plannify-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-plannify-dev
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/rewrite-target: /
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: api-dev.plannify.be
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: plannify-dev-admin-api
                port:
                  number: 80
  tls:
    - hosts:
        - api-dev.plannify.be
      secretName: dev-api-plannify-be-tls
