apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: plannify-dev-project
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/plannify-truck-driver-app/admin-api.git
  destinations:
    - namespace: plannify-dev
      server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-plannify-applications
  namespace: argocd
spec:
  project: plannify-dev-project
  source:
    repoURL: git@github.com:plannify-truck-driver-app/infrastructure.git
    targetRevision: main
    path: argocd-applications/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true